export { default as pages } from "./schemas/documents/pages"

//sections
export { default as appPromo } from "./schemas/sections/app_promo/appPromo"
export { default as blog } from "./schemas/sections/blog/blog"
export { default as callToAction } from "./schemas/sections/call_to_action/callToAction"
export { default as contact } from "./schemas/sections/contact/contact"
export { default as cookies } from "./schemas/sections/cookies/cookies"
export { default as faqs } from "./schemas/sections/faqs/faqs"
export { default as features } from "./schemas/sections/features/features"
export { default as footer } from "./schemas/sections/footer/footer"
export { default as header } from "./schemas/sections/header/header"
export { default as howItWorks } from "./schemas/sections/how_it_works/howItWorks"
export { default as logoCloud } from "./schemas/sections/logo_cloud/logoCloud"
export { default as navigation } from "./schemas/sections/navigation/navigation"
export { default as newsletter } from "./schemas/sections/newsletter/newsletter"
export { default as portfolio } from "./schemas/sections/portfolio/portfolio"
export { default as pricing } from "./schemas/sections/pricing/pricing"
export { default as stats } from "./schemas/sections/stats/stats"
export { default as team } from "./schemas/sections/team/team"
export { default as testimonial } from "./schemas/sections/testimonial/testimonial"

//elements
export { default as image } from "./schemas/elements/image"
export { default as externalLink } from "./schemas/elements/externalLink"
export { default as internalLink } from "./schemas/elements/internalLink"
export { default as socialMedia } from "./schemas/elements/socialMedia"
export { default as hero } from "./schemas/elements/hero"
export { default as pricingDetail } from "./schemas/elements/pricingDetail"
export { default as addButton } from "./schemas/elements/addButton"
export { default as featureItem } from "./schemas/elements/featureItem"
export { default as testimonialSource } from "./schemas/elements/testimonialSource"
export { default as youtube } from "./schemas/elements/youtube"
export { default as person } from "./schemas/elements/person"
export { default as questionsAsked } from "./schemas/elements/questionsAsked"
export { default as steps } from "./schemas/elements/steps"
export { default as statsItem } from "./schemas/elements/statsItem"
export { default as blogPost } from "./schemas/elements/blogPost"
